### ISSUE TITLE
[BUG] Okta and PING unable to Enroll (SAML) 

### ISSUE THREAD

**Issue by PrivateBio** [openinfer/PrivateIdentity#23]
**Describe the bug**
CV undefined error.  (In production) 

**Screenshots**
![Okta Error Console 6-14-2020](https://user-images.githubusercontent.com/46856299/84597311-2a07b480-ae31-11ea-8549-fd29c93437e0.png)

**Desktop (please complete the following information):**
 - OS: Chrome on Win10 laptop

**Comment by sriesow** [comment]
@loainagati @nikita-lazarev-up This bug seems to happen in /a or /factor as the normal URL predict is also giving the same error. It seems to be OpenCV import is not found but couldn't find the exact place it is importing.

![Screenshot 2020-06-15 at 1 00 09 PM](https://user-images.githubusercontent.com/19872048/84629585-2f83fe00-af08-11ea-9d98-a1546e3230c9.png)
